services:
  freeglm:
    image: ghcr.io/devil666face/freeglm:latest
    container_name: freeglm
    restart: unless-stopped
    stop_grace_period: 5s
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ZAI_API_KEY=$ZAI_API_KEY
    volumes:
      - ./db:/freeglm/db
    cap_add:
      - NET_ADMIN
    network_mode: "host"
